// flow-typed signature: 3b107deb460a950459244b1600b33609
// flow-typed version: <<STUB>>/chessboardjs_v^0.0.1/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chessboardjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'chessboardjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'chessboardjs/www/js/chess' {
  declare module.exports: any;
}

declare module 'chessboardjs/www/js/chessboard' {
  declare module.exports: any;
}

declare module 'chessboardjs/www/js/home' {
  declare module.exports: any;
}

declare module 'chessboardjs/www/js/jquery-1.10.1.min' {
  declare module.exports: any;
}

declare module 'chessboardjs/www/js/jquery.color.min' {
  declare module.exports: any;
}

declare module 'chessboardjs/www/js/json3.min' {
  declare module.exports: any;
}

declare module 'chessboardjs/www/js/prettify' {
  declare module.exports: any;
}

declare module 'chessboardjs/www/releases/0.1.0/js/chessboard-0.1.0' {
  declare module.exports: any;
}

declare module 'chessboardjs/www/releases/0.1.0/js/chessboard-0.1.0.min' {
  declare module.exports: any;
}

declare module 'chessboardjs/www/releases/0.2.0/js/chessboard-0.2.0' {
  declare module.exports: any;
}

declare module 'chessboardjs/www/releases/0.2.0/js/chessboard-0.2.0.min' {
  declare module.exports: any;
}

declare module 'chessboardjs/www/releases/0.3.0/js/chessboard-0.3.0' {
  declare module.exports: any;
}

declare module 'chessboardjs/www/releases/0.3.0/js/chessboard-0.3.0.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'chessboardjs/www/js/chess.js' {
  declare module.exports: $Exports<'chessboardjs/www/js/chess'>;
}
declare module 'chessboardjs/www/js/chessboard.js' {
  declare module.exports: $Exports<'chessboardjs/www/js/chessboard'>;
}
declare module 'chessboardjs/www/js/home.js' {
  declare module.exports: $Exports<'chessboardjs/www/js/home'>;
}
declare module 'chessboardjs/www/js/jquery-1.10.1.min.js' {
  declare module.exports: $Exports<'chessboardjs/www/js/jquery-1.10.1.min'>;
}
declare module 'chessboardjs/www/js/jquery.color.min.js' {
  declare module.exports: $Exports<'chessboardjs/www/js/jquery.color.min'>;
}
declare module 'chessboardjs/www/js/json3.min.js' {
  declare module.exports: $Exports<'chessboardjs/www/js/json3.min'>;
}
declare module 'chessboardjs/www/js/prettify.js' {
  declare module.exports: $Exports<'chessboardjs/www/js/prettify'>;
}
declare module 'chessboardjs/www/releases/0.1.0/js/chessboard-0.1.0.js' {
  declare module.exports: $Exports<'chessboardjs/www/releases/0.1.0/js/chessboard-0.1.0'>;
}
declare module 'chessboardjs/www/releases/0.1.0/js/chessboard-0.1.0.min.js' {
  declare module.exports: $Exports<'chessboardjs/www/releases/0.1.0/js/chessboard-0.1.0.min'>;
}
declare module 'chessboardjs/www/releases/0.2.0/js/chessboard-0.2.0.js' {
  declare module.exports: $Exports<'chessboardjs/www/releases/0.2.0/js/chessboard-0.2.0'>;
}
declare module 'chessboardjs/www/releases/0.2.0/js/chessboard-0.2.0.min.js' {
  declare module.exports: $Exports<'chessboardjs/www/releases/0.2.0/js/chessboard-0.2.0.min'>;
}
declare module 'chessboardjs/www/releases/0.3.0/js/chessboard-0.3.0.js' {
  declare module.exports: $Exports<'chessboardjs/www/releases/0.3.0/js/chessboard-0.3.0'>;
}
declare module 'chessboardjs/www/releases/0.3.0/js/chessboard-0.3.0.min.js' {
  declare module.exports: $Exports<'chessboardjs/www/releases/0.3.0/js/chessboard-0.3.0.min'>;
}
