// flow-typed signature: 607cf8649ecc3df522373288e1e1030c
// flow-typed version: <<STUB>>/clean-documentation-theme_v^0.5.2/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'clean-documentation-theme'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'clean-documentation-theme' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'clean-documentation-theme/dist/index' {
  declare module.exports: any;
}

declare module 'clean-documentation-theme/dist/index.min' {
  declare module.exports: any;
}

declare module 'clean-documentation-theme/lib/components/app' {
  declare module.exports: any;
}

declare module 'clean-documentation-theme/lib/components/content/description' {
  declare module.exports: any;
}

declare module 'clean-documentation-theme/lib/components/content/example' {
  declare module.exports: any;
}

declare module 'clean-documentation-theme/lib/components/content/examples' {
  declare module.exports: any;
}

declare module 'clean-documentation-theme/lib/components/content/extends' {
  declare module.exports: any;
}

declare module 'clean-documentation-theme/lib/components/content/index' {
  declare module.exports: any;
}

declare module 'clean-documentation-theme/lib/components/content/param' {
  declare module.exports: any;
}

declare module 'clean-documentation-theme/lib/components/content/params' {
  declare module.exports: any;
}

declare module 'clean-documentation-theme/lib/components/content/returns' {
  declare module.exports: any;
}

declare module 'clean-documentation-theme/lib/components/content/section-group' {
  declare module.exports: any;
}

declare module 'clean-documentation-theme/lib/components/content/section-member' {
  declare module.exports: any;
}

declare module 'clean-documentation-theme/lib/components/content/section' {
  declare module.exports: any;
}

declare module 'clean-documentation-theme/lib/components/content/see' {
  declare module.exports: any;
}

declare module 'clean-documentation-theme/lib/components/content/signature' {
  declare module.exports: any;
}

declare module 'clean-documentation-theme/lib/components/content/source-link' {
  declare module.exports: any;
}

declare module 'clean-documentation-theme/lib/components/content/throws' {
  declare module.exports: any;
}

declare module 'clean-documentation-theme/lib/components/content/type' {
  declare module.exports: any;
}

declare module 'clean-documentation-theme/lib/components/header' {
  declare module.exports: any;
}

declare module 'clean-documentation-theme/lib/components/html' {
  declare module.exports: any;
}

declare module 'clean-documentation-theme/lib/components/navigation' {
  declare module.exports: any;
}

declare module 'clean-documentation-theme/lib/components/styles' {
  declare module.exports: any;
}

declare module 'clean-documentation-theme/lib/index' {
  declare module.exports: any;
}

declare module 'clean-documentation-theme/lib/utils' {
  declare module.exports: any;
}

declare module 'clean-documentation-theme/src/components/app' {
  declare module.exports: any;
}

declare module 'clean-documentation-theme/src/components/content/description' {
  declare module.exports: any;
}

declare module 'clean-documentation-theme/src/components/content/example' {
  declare module.exports: any;
}

declare module 'clean-documentation-theme/src/components/content/examples' {
  declare module.exports: any;
}

declare module 'clean-documentation-theme/src/components/content/extends' {
  declare module.exports: any;
}

declare module 'clean-documentation-theme/src/components/content/index' {
  declare module.exports: any;
}

declare module 'clean-documentation-theme/src/components/content/param' {
  declare module.exports: any;
}

declare module 'clean-documentation-theme/src/components/content/params' {
  declare module.exports: any;
}

declare module 'clean-documentation-theme/src/components/content/returns' {
  declare module.exports: any;
}

declare module 'clean-documentation-theme/src/components/content/section-group' {
  declare module.exports: any;
}

declare module 'clean-documentation-theme/src/components/content/section-member' {
  declare module.exports: any;
}

declare module 'clean-documentation-theme/src/components/content/section' {
  declare module.exports: any;
}

declare module 'clean-documentation-theme/src/components/content/see' {
  declare module.exports: any;
}

declare module 'clean-documentation-theme/src/components/content/signature' {
  declare module.exports: any;
}

declare module 'clean-documentation-theme/src/components/content/source-link' {
  declare module.exports: any;
}

declare module 'clean-documentation-theme/src/components/content/throws' {
  declare module.exports: any;
}

declare module 'clean-documentation-theme/src/components/content/type' {
  declare module.exports: any;
}

declare module 'clean-documentation-theme/src/components/header' {
  declare module.exports: any;
}

declare module 'clean-documentation-theme/src/components/html' {
  declare module.exports: any;
}

declare module 'clean-documentation-theme/src/components/navigation' {
  declare module.exports: any;
}

declare module 'clean-documentation-theme/src/components/styles' {
  declare module.exports: any;
}

declare module 'clean-documentation-theme/src/index' {
  declare module.exports: any;
}

declare module 'clean-documentation-theme/src/utils' {
  declare module.exports: any;
}

declare module 'clean-documentation-theme/test/components/app-test' {
  declare module.exports: any;
}

declare module 'clean-documentation-theme/test/components/extends-test' {
  declare module.exports: any;
}

declare module 'clean-documentation-theme/test/components/index.spec' {
  declare module.exports: any;
}

declare module 'clean-documentation-theme/test/components/returns-test' {
  declare module.exports: any;
}

declare module 'clean-documentation-theme/test/components/see-test' {
  declare module.exports: any;
}

declare module 'clean-documentation-theme/test/components/source-link-test' {
  declare module.exports: any;
}

declare module 'clean-documentation-theme/test/components/throws-test' {
  declare module.exports: any;
}

declare module 'clean-documentation-theme/test/utils.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'clean-documentation-theme/dist/index.js' {
  declare module.exports: $Exports<'clean-documentation-theme/dist/index'>;
}
declare module 'clean-documentation-theme/dist/index.min.js' {
  declare module.exports: $Exports<'clean-documentation-theme/dist/index.min'>;
}
declare module 'clean-documentation-theme/lib/components/app.js' {
  declare module.exports: $Exports<'clean-documentation-theme/lib/components/app'>;
}
declare module 'clean-documentation-theme/lib/components/content/description.js' {
  declare module.exports: $Exports<'clean-documentation-theme/lib/components/content/description'>;
}
declare module 'clean-documentation-theme/lib/components/content/example.js' {
  declare module.exports: $Exports<'clean-documentation-theme/lib/components/content/example'>;
}
declare module 'clean-documentation-theme/lib/components/content/examples.js' {
  declare module.exports: $Exports<'clean-documentation-theme/lib/components/content/examples'>;
}
declare module 'clean-documentation-theme/lib/components/content/extends.js' {
  declare module.exports: $Exports<'clean-documentation-theme/lib/components/content/extends'>;
}
declare module 'clean-documentation-theme/lib/components/content/index.js' {
  declare module.exports: $Exports<'clean-documentation-theme/lib/components/content/index'>;
}
declare module 'clean-documentation-theme/lib/components/content/param.js' {
  declare module.exports: $Exports<'clean-documentation-theme/lib/components/content/param'>;
}
declare module 'clean-documentation-theme/lib/components/content/params.js' {
  declare module.exports: $Exports<'clean-documentation-theme/lib/components/content/params'>;
}
declare module 'clean-documentation-theme/lib/components/content/returns.js' {
  declare module.exports: $Exports<'clean-documentation-theme/lib/components/content/returns'>;
}
declare module 'clean-documentation-theme/lib/components/content/section-group.js' {
  declare module.exports: $Exports<'clean-documentation-theme/lib/components/content/section-group'>;
}
declare module 'clean-documentation-theme/lib/components/content/section-member.js' {
  declare module.exports: $Exports<'clean-documentation-theme/lib/components/content/section-member'>;
}
declare module 'clean-documentation-theme/lib/components/content/section.js' {
  declare module.exports: $Exports<'clean-documentation-theme/lib/components/content/section'>;
}
declare module 'clean-documentation-theme/lib/components/content/see.js' {
  declare module.exports: $Exports<'clean-documentation-theme/lib/components/content/see'>;
}
declare module 'clean-documentation-theme/lib/components/content/signature.js' {
  declare module.exports: $Exports<'clean-documentation-theme/lib/components/content/signature'>;
}
declare module 'clean-documentation-theme/lib/components/content/source-link.js' {
  declare module.exports: $Exports<'clean-documentation-theme/lib/components/content/source-link'>;
}
declare module 'clean-documentation-theme/lib/components/content/throws.js' {
  declare module.exports: $Exports<'clean-documentation-theme/lib/components/content/throws'>;
}
declare module 'clean-documentation-theme/lib/components/content/type.js' {
  declare module.exports: $Exports<'clean-documentation-theme/lib/components/content/type'>;
}
declare module 'clean-documentation-theme/lib/components/header.js' {
  declare module.exports: $Exports<'clean-documentation-theme/lib/components/header'>;
}
declare module 'clean-documentation-theme/lib/components/html.js' {
  declare module.exports: $Exports<'clean-documentation-theme/lib/components/html'>;
}
declare module 'clean-documentation-theme/lib/components/navigation.js' {
  declare module.exports: $Exports<'clean-documentation-theme/lib/components/navigation'>;
}
declare module 'clean-documentation-theme/lib/components/styles.js' {
  declare module.exports: $Exports<'clean-documentation-theme/lib/components/styles'>;
}
declare module 'clean-documentation-theme/lib/index.js' {
  declare module.exports: $Exports<'clean-documentation-theme/lib/index'>;
}
declare module 'clean-documentation-theme/lib/utils.js' {
  declare module.exports: $Exports<'clean-documentation-theme/lib/utils'>;
}
declare module 'clean-documentation-theme/src/components/app.js' {
  declare module.exports: $Exports<'clean-documentation-theme/src/components/app'>;
}
declare module 'clean-documentation-theme/src/components/content/description.js' {
  declare module.exports: $Exports<'clean-documentation-theme/src/components/content/description'>;
}
declare module 'clean-documentation-theme/src/components/content/example.js' {
  declare module.exports: $Exports<'clean-documentation-theme/src/components/content/example'>;
}
declare module 'clean-documentation-theme/src/components/content/examples.js' {
  declare module.exports: $Exports<'clean-documentation-theme/src/components/content/examples'>;
}
declare module 'clean-documentation-theme/src/components/content/extends.js' {
  declare module.exports: $Exports<'clean-documentation-theme/src/components/content/extends'>;
}
declare module 'clean-documentation-theme/src/components/content/index.js' {
  declare module.exports: $Exports<'clean-documentation-theme/src/components/content/index'>;
}
declare module 'clean-documentation-theme/src/components/content/param.js' {
  declare module.exports: $Exports<'clean-documentation-theme/src/components/content/param'>;
}
declare module 'clean-documentation-theme/src/components/content/params.js' {
  declare module.exports: $Exports<'clean-documentation-theme/src/components/content/params'>;
}
declare module 'clean-documentation-theme/src/components/content/returns.js' {
  declare module.exports: $Exports<'clean-documentation-theme/src/components/content/returns'>;
}
declare module 'clean-documentation-theme/src/components/content/section-group.js' {
  declare module.exports: $Exports<'clean-documentation-theme/src/components/content/section-group'>;
}
declare module 'clean-documentation-theme/src/components/content/section-member.js' {
  declare module.exports: $Exports<'clean-documentation-theme/src/components/content/section-member'>;
}
declare module 'clean-documentation-theme/src/components/content/section.js' {
  declare module.exports: $Exports<'clean-documentation-theme/src/components/content/section'>;
}
declare module 'clean-documentation-theme/src/components/content/see.js' {
  declare module.exports: $Exports<'clean-documentation-theme/src/components/content/see'>;
}
declare module 'clean-documentation-theme/src/components/content/signature.js' {
  declare module.exports: $Exports<'clean-documentation-theme/src/components/content/signature'>;
}
declare module 'clean-documentation-theme/src/components/content/source-link.js' {
  declare module.exports: $Exports<'clean-documentation-theme/src/components/content/source-link'>;
}
declare module 'clean-documentation-theme/src/components/content/throws.js' {
  declare module.exports: $Exports<'clean-documentation-theme/src/components/content/throws'>;
}
declare module 'clean-documentation-theme/src/components/content/type.js' {
  declare module.exports: $Exports<'clean-documentation-theme/src/components/content/type'>;
}
declare module 'clean-documentation-theme/src/components/header.js' {
  declare module.exports: $Exports<'clean-documentation-theme/src/components/header'>;
}
declare module 'clean-documentation-theme/src/components/html.js' {
  declare module.exports: $Exports<'clean-documentation-theme/src/components/html'>;
}
declare module 'clean-documentation-theme/src/components/navigation.js' {
  declare module.exports: $Exports<'clean-documentation-theme/src/components/navigation'>;
}
declare module 'clean-documentation-theme/src/components/styles.js' {
  declare module.exports: $Exports<'clean-documentation-theme/src/components/styles'>;
}
declare module 'clean-documentation-theme/src/index.js' {
  declare module.exports: $Exports<'clean-documentation-theme/src/index'>;
}
declare module 'clean-documentation-theme/src/utils.js' {
  declare module.exports: $Exports<'clean-documentation-theme/src/utils'>;
}
declare module 'clean-documentation-theme/test/components/app-test.js' {
  declare module.exports: $Exports<'clean-documentation-theme/test/components/app-test'>;
}
declare module 'clean-documentation-theme/test/components/extends-test.js' {
  declare module.exports: $Exports<'clean-documentation-theme/test/components/extends-test'>;
}
declare module 'clean-documentation-theme/test/components/index.spec.js' {
  declare module.exports: $Exports<'clean-documentation-theme/test/components/index.spec'>;
}
declare module 'clean-documentation-theme/test/components/returns-test.js' {
  declare module.exports: $Exports<'clean-documentation-theme/test/components/returns-test'>;
}
declare module 'clean-documentation-theme/test/components/see-test.js' {
  declare module.exports: $Exports<'clean-documentation-theme/test/components/see-test'>;
}
declare module 'clean-documentation-theme/test/components/source-link-test.js' {
  declare module.exports: $Exports<'clean-documentation-theme/test/components/source-link-test'>;
}
declare module 'clean-documentation-theme/test/components/throws-test.js' {
  declare module.exports: $Exports<'clean-documentation-theme/test/components/throws-test'>;
}
declare module 'clean-documentation-theme/test/utils.spec.js' {
  declare module.exports: $Exports<'clean-documentation-theme/test/utils.spec'>;
}
