// flow-typed signature: 091dae2f2695c47af1f6fff6dbce79de
// flow-typed version: <<STUB>>/vue-jest_v^1.0.2/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-jest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-jest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-jest/build/gen-release-note' {
  declare module.exports: any;
}

declare module 'vue-jest/lib/add-template-mapping' {
  declare module.exports: any;
}

declare module 'vue-jest/lib/cache' {
  declare module.exports: any;
}

declare module 'vue-jest/lib/compilers/babel-compiler' {
  declare module.exports: any;
}

declare module 'vue-jest/lib/compilers/coffee-compiler' {
  declare module.exports: any;
}

declare module 'vue-jest/lib/compilers/haml-compiler' {
  declare module.exports: any;
}

declare module 'vue-jest/lib/compilers/jade-compiler' {
  declare module.exports: any;
}

declare module 'vue-jest/lib/compilers/pug-compiler' {
  declare module.exports: any;
}

declare module 'vue-jest/lib/compilers/typescript-compiler' {
  declare module.exports: any;
}

declare module 'vue-jest/lib/ensure-require' {
  declare module.exports: any;
}

declare module 'vue-jest/lib/extract-props' {
  declare module.exports: any;
}

declare module 'vue-jest/lib/generate-source-map' {
  declare module.exports: any;
}

declare module 'vue-jest/lib/get_cache_key' {
  declare module.exports: any;
}

declare module 'vue-jest/lib/load-babel-config' {
  declare module.exports: any;
}

declare module 'vue-jest/lib/logger' {
  declare module.exports: any;
}

declare module 'vue-jest/lib/process' {
  declare module.exports: any;
}

declare module 'vue-jest/lib/template-compiler' {
  declare module.exports: any;
}

declare module 'vue-jest/lib/throw-error' {
  declare module.exports: any;
}

declare module 'vue-jest/test/Babel.spec' {
  declare module.exports: any;
}

declare module 'vue-jest/test/coffee.spec' {
  declare module.exports: any;
}

declare module 'vue-jest/test/extract-props.spec' {
  declare module.exports: any;
}

declare module 'vue-jest/test/FunctionalSFC.spec' {
  declare module.exports: any;
}

declare module 'vue-jest/test/FunctionalSFCParent.spec' {
  declare module.exports: any;
}

declare module 'vue-jest/test/jade.spec' {
  declare module.exports: any;
}

declare module 'vue-jest/test/load-babel-config.spec' {
  declare module.exports: any;
}

declare module 'vue-jest/test/NoScript.spec' {
  declare module.exports: any;
}

declare module 'vue-jest/test/pug.spec' {
  declare module.exports: any;
}

declare module 'vue-jest/test/RenderFunction.spec' {
  declare module.exports: any;
}

declare module 'vue-jest/test/resources/BasicSrc' {
  declare module.exports: any;
}

declare module 'vue-jest/test/TypeScript.spec' {
  declare module.exports: any;
}

declare module 'vue-jest/vue-jest' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-jest/build/gen-release-note.js' {
  declare module.exports: $Exports<'vue-jest/build/gen-release-note'>;
}
declare module 'vue-jest/lib/add-template-mapping.js' {
  declare module.exports: $Exports<'vue-jest/lib/add-template-mapping'>;
}
declare module 'vue-jest/lib/cache.js' {
  declare module.exports: $Exports<'vue-jest/lib/cache'>;
}
declare module 'vue-jest/lib/compilers/babel-compiler.js' {
  declare module.exports: $Exports<'vue-jest/lib/compilers/babel-compiler'>;
}
declare module 'vue-jest/lib/compilers/coffee-compiler.js' {
  declare module.exports: $Exports<'vue-jest/lib/compilers/coffee-compiler'>;
}
declare module 'vue-jest/lib/compilers/haml-compiler.js' {
  declare module.exports: $Exports<'vue-jest/lib/compilers/haml-compiler'>;
}
declare module 'vue-jest/lib/compilers/jade-compiler.js' {
  declare module.exports: $Exports<'vue-jest/lib/compilers/jade-compiler'>;
}
declare module 'vue-jest/lib/compilers/pug-compiler.js' {
  declare module.exports: $Exports<'vue-jest/lib/compilers/pug-compiler'>;
}
declare module 'vue-jest/lib/compilers/typescript-compiler.js' {
  declare module.exports: $Exports<'vue-jest/lib/compilers/typescript-compiler'>;
}
declare module 'vue-jest/lib/ensure-require.js' {
  declare module.exports: $Exports<'vue-jest/lib/ensure-require'>;
}
declare module 'vue-jest/lib/extract-props.js' {
  declare module.exports: $Exports<'vue-jest/lib/extract-props'>;
}
declare module 'vue-jest/lib/generate-source-map.js' {
  declare module.exports: $Exports<'vue-jest/lib/generate-source-map'>;
}
declare module 'vue-jest/lib/get_cache_key.js' {
  declare module.exports: $Exports<'vue-jest/lib/get_cache_key'>;
}
declare module 'vue-jest/lib/load-babel-config.js' {
  declare module.exports: $Exports<'vue-jest/lib/load-babel-config'>;
}
declare module 'vue-jest/lib/logger.js' {
  declare module.exports: $Exports<'vue-jest/lib/logger'>;
}
declare module 'vue-jest/lib/process.js' {
  declare module.exports: $Exports<'vue-jest/lib/process'>;
}
declare module 'vue-jest/lib/template-compiler.js' {
  declare module.exports: $Exports<'vue-jest/lib/template-compiler'>;
}
declare module 'vue-jest/lib/throw-error.js' {
  declare module.exports: $Exports<'vue-jest/lib/throw-error'>;
}
declare module 'vue-jest/test/Babel.spec.js' {
  declare module.exports: $Exports<'vue-jest/test/Babel.spec'>;
}
declare module 'vue-jest/test/coffee.spec.js' {
  declare module.exports: $Exports<'vue-jest/test/coffee.spec'>;
}
declare module 'vue-jest/test/extract-props.spec.js' {
  declare module.exports: $Exports<'vue-jest/test/extract-props.spec'>;
}
declare module 'vue-jest/test/FunctionalSFC.spec.js' {
  declare module.exports: $Exports<'vue-jest/test/FunctionalSFC.spec'>;
}
declare module 'vue-jest/test/FunctionalSFCParent.spec.js' {
  declare module.exports: $Exports<'vue-jest/test/FunctionalSFCParent.spec'>;
}
declare module 'vue-jest/test/jade.spec.js' {
  declare module.exports: $Exports<'vue-jest/test/jade.spec'>;
}
declare module 'vue-jest/test/load-babel-config.spec.js' {
  declare module.exports: $Exports<'vue-jest/test/load-babel-config.spec'>;
}
declare module 'vue-jest/test/NoScript.spec.js' {
  declare module.exports: $Exports<'vue-jest/test/NoScript.spec'>;
}
declare module 'vue-jest/test/pug.spec.js' {
  declare module.exports: $Exports<'vue-jest/test/pug.spec'>;
}
declare module 'vue-jest/test/RenderFunction.spec.js' {
  declare module.exports: $Exports<'vue-jest/test/RenderFunction.spec'>;
}
declare module 'vue-jest/test/resources/BasicSrc.js' {
  declare module.exports: $Exports<'vue-jest/test/resources/BasicSrc'>;
}
declare module 'vue-jest/test/TypeScript.spec.js' {
  declare module.exports: $Exports<'vue-jest/test/TypeScript.spec'>;
}
declare module 'vue-jest/vue-jest.js' {
  declare module.exports: $Exports<'vue-jest/vue-jest'>;
}
